apiVersion: v1
kind: Secret
metadata:
  name: kafka-secret
data:
  KAFKA_LISTENERS: UExBSU5URVhUOi8vOjkwOTI=
  KAFKA_ADVERTISED_LISTENERS: UExBSU5URVhUOi8vMTI3LjAuMC4xOjkwOTI=
  KAFKA_ZOOKEEPER_CONNECT: MTAuMTAwLjM0Ljg6MjE4MQ==